[package]
name = "howmanysmall/typed-promise"
description = "Promises with types"
version = "4.0.3"
license = "MIT"
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"

[dependencies]
Promise = "evaera/promise@4.0.0"
